name: squirrel
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.74
  - minimap2>=2.17
  - python
  - snakemake-minimal
  - matplotlib>=3.3.1
  - gofasta
  - iqtree>=2.1
  - jclusterfunk>=0.0.25
